spring:
  cloud:
    #################################
    #   gateway相关配置
    #################################
    gateway:
      ################################
      # 配置允许跨域请求
      ################################
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
      #    路由定义
      routes:
        #    本地服务器
        - id: property
          uri: http://localhost:8090/api/property/
          predicates:
            - Path=/api/property/**
        - id: org
          uri: http://localhost:8092/api/org/
          predicates:
            - Path=/api/org/**
        - id: profit
          uri: http://localhost:8091/api/profit/
          predicates:
            - Path=/api/profit/**
        - id: wechat
          uri: http://localhost:8090/api/wechat/
          predicates:
            - Path=/api/wechat/**
        - id: payment
          uri: http://localhost:8099/api/payment/
          predicates:
            - Path=/api/payment/**
# 配置jwt一些常用参数
org:
  my:
    jwt:
      # token有效期 秒
      effective-time: 7200
      # 登陆调用URL
      auth-uri: http://localhost:8090/api/property/admin/loginTest
      # 用户基本信息URL
      userInfo-uri: http://localhost:8090/api/property/admin/getUserInfoTest

